In [1]:
import numpy as np

별칭(alias)은 주로 np를 사용합니다.

In [2]:
np.__version__

'1.25.2'

In [3]:
mylist1 = [1, 2, 3]
mylist2 = [4, 5, 6]

In [4]:
type(mylist1)

list

리스트(list)는 확장성에는 용이하지만, 수치계산(numerical calculation)이 어렵습니다.

만약, mylist1과 mylist2를 더하는 연산을 하고 싶지만, 이를 지원하지 않습니다. 뿐만 아니라 머신러닝에서 중요한 2차원의 행렬연산이나 고차원 연산도 지원하지 않습니다.

In [5]:
mylist1 + mylist2

[1, 2, 3, 4, 5, 6]

In [6]:
answer = []
for i in range(len(mylist1)):
    answer.append(mylist1[i]+mylist2[i])
answer

[5, 7, 9]

배열(Array)

numpy의 배열은 동일한 type을 가집니다.

파이썬의 list로는 고성능 수치계산이 어렵기 때문에 numpy의 배열로 수치계산을 수행합니다.

In [7]:
myarray = np.array([1, 2, 3])
myarray

array([1, 2, 3])

type은 ndarray로 생성되는 것을 볼 수 있는데, n-dimensional array(N차원 배열) type입니다.

In [8]:
type(myarray)

numpy.ndarray

ndim은 배열의 차원을 나타냅니다.

In [9]:
myarray.ndim

1

중첩된 리스트(list)로 생성시 2차원 배열이 생성됩니다.

In [10]:
myarray2 = np.array([[1, 2, 3], [4, 5, 6]])
myarray2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
myarray2.ndim

2

shape: 크기 확인

shape는 튜플(tuple) 형태로 출력됩니다.

In [12]:
myarray.shape

(3,)

In [13]:
myarray2.shape

(2, 3)

dtype: 타입 확인

In [14]:
myarray = np.array([[1, 2, 3], [4, 5, 6]])
myarray

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
myarray.dtype

dtype('int64')

dtype을 지정하여 생성할 수 있습니다.

In [17]:
myarray = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
myarray

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
myarray.dtype

dtype('float64')

size: 총 요소의 수

In [19]:
myarray = np.array([1, 2, 3])
myarray

array([1, 2, 3])

In [20]:
myarray.size

3

In [21]:
myarray = np.array([[1, 2, 3], [4, 5, 6]])
myarray

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
myarray.size

6

T: 전치(transpose), 행과 열의 교환

In [23]:
myarray = np.array([1, 2, 3])
myarray

array([1, 2, 3])

In [24]:
myarray.T

array([1, 2, 3])

In [25]:
myarray = np.array([[1, 2, 3], [4, 5, 6]])
myarray

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
myarray.T

array([[1, 4],
       [2, 5],
       [3, 6]])

arange(): 생성

np.arange()는 파이썬의 range()와 유사하며 범위를 통해 배열(array)을 생성합니다.
np.arange(start, stop, step)

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

linspace(): 범위 내 균일하게 생성

np.linspace()는 수의 범위를 균일하게 나누고자 할 때 사용


np.linspace(start, stop, count): start 부터 stop 까지 count개 구간으로 나눕니다.

In [31]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

zeros(), ones(), full()

np.zeros(): 0으로 채워진 배열 생성

np.ones(): 1로 채워진 배열 생성

np.full(shape, fill_value): 지정한 값(fill_value)으로 채워진 배열 생성

In [32]:
np.zeros(shape=(3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones(shape=(3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.full(shape=(3, 3), fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

eye()

identical matrix 생성

대각 방향으로 1로 채워진 행렬

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

random.randn(): 난수 생성

정규 분포 범위내의 난수(random) 생성

In [36]:
np.random.randn(10)

array([ 0.08494045, -0.5367708 ,  0.53917726, -0.78667391,  0.09022369,
       -0.22851952,  0.60622775, -0.5101755 , -0.46902585,  0.47975311])

인덱싱(indexing)

In [37]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [38]:
arr1[0]

1

In [39]:
arr2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15]
                ])

In [40]:
list2=[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15]
                ]
list2

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [41]:
list2[2][3]

14

In [44]:
list2[2, 3]

TypeError: list indices must be integers or slices, not tuple

In [42]:
arr2[2, 3]

14

In [43]:
arr2[2][3]

14

슬라이싱(slicing)

In [45]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [46]:
arr1[:2]

array([1, 2])

In [47]:
arr1[-2:]

array([4, 5])

2차원 배열

In [48]:
arr2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15]
                ])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [49]:
arr2[:, 1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [50]:
arr2[:2, 1:3]

array([[2, 3],
       [7, 8]])

reshape: 형태 변경

형태(shape)는 자유롭게 변경이 가능하나 변경 후의 데이터 개수(size)는 변경 전과 같아야 합니다.

-1은 자동으로 크기를 계산합니다.

In [51]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
arr.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
arr.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [54]:
arr.reshape(-1, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

행열 연산

In [55]:
x = np.array([[10, 20], [30, 40]])
y = np.array([[5, 6], [7, 8]])

In [56]:
x + y

array([[15, 26],
       [37, 48]])

In [57]:
x * y

array([[ 50, 120],
       [210, 320]])

In [58]:
x - y

array([[ 5, 14],
       [23, 32]])

In [59]:
x / y

array([[2.        , 3.33333333],
       [4.28571429, 5.        ]])

In [60]:
x % y

array([[0, 2],
       [2, 0]])

In [61]:
x // y

array([[2, 3],
       [4, 5]])

# shape가 맞지 않으면 안됩니다!

In [62]:
x = np.array([[1, 2, 3], [3, 4, 5]])
y = np.array([[5, 6, ], [7, 8]])

In [63]:
x + y

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [64]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [65]:
x + 10

array([[11, 12],
       [13, 14]])

In [66]:
x ** 2

array([[ 1,  4],
       [ 9, 16]])

In [67]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

행렬의 곱연산

*: 일반 곱셈 부호

@: matmul, 행열의 곱연산, 내적곱(dot product)

In [68]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [69]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

일반 곱을 수행한 결과

In [70]:
a * b

array([[ 5, 12],
       [21, 32]])

행렬곱을 수행한 결과

In [71]:
a @ b

array([[19, 22],
       [43, 50]])

Boolean Indexing

조건 배열(Boolean array)을 활용하여 인덱싱하는 방법입니다.

조건에 해당하는 결과가 True인 요소를 반환합니다.

인덱싱 후 결과는 항상 1차원 배열로 반환합니다.

In [72]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
# Boolean 배열 생성
bool_arr = arr > 5
bool_arr

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [74]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10, 11, 12])

Fancy Indexing

다른 배열(array)이나 리스트(list)를 사용하여 배열을 인덱싱 하는 방법입니다.

In [75]:
arr = np.arange(100, 110)
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [76]:
# 인덱스 리스트 생성
idx = [0, 2, 5]
arr[idx]

array([100, 102, 105])

np.arange()로 인덱스를 생성할 배열 생성후 fancy indexing 합니다.

In [77]:
# np.arange로 인덱스 생성
arr_idx = np.arange(1, 9, 2)
arr_idx

array([1, 3, 5, 7])

In [78]:
arr[arr_idx]

array([101, 103, 105, 107])

배열 참조

배열을 슬라이싱 한 후 결과 값은 원본 배열을 참조(reference)합니다.

따라서, 슬라이싱한 배열 수정시 원본 배열에서도 수정되는 현상이 발생합니다.

In [79]:
a = np.arange(1, 13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
# 슬라이싱으로 a1 생성
a1 = a[:5]
a1

array([1, 2, 3, 4, 5])

In [81]:
a1[0] = 999
a

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [82]:
# 값을 참조하기 때문에 원본 데이터도 수정된다.
print(f'a  : {a}')
print(f'a1 : {a1}')

a  : [999   2   3   4   5   6   7   8   9  10  11  12]
a1 : [999   2   3   4   5]
